trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
# pool:
#   name: Self-Hosted

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest tests/ --junitxml=junit/test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'junit/test-results.xml'
    testRunTitle: 'Pytest Results'

# SonarQube Cloud
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarQube Cloud'
    organization: 'nexadeepls'
    scannerMode: 'cli'
    cliScannerVersion: '6.2.1.4610'
    configMode: 'manual'
    cliProjectKey: 'nexadeepls_CDC'
    cliProjectName: 'CDC'
    cliSources: '.'
  displayName: 'Prepare SonarCloud Analysis'